### ISSUE TITLE
Designing  of  gRNA for CRISPR-Cas system gRNA

### ISSUE THREAD

**Issue by tiramisutes** [meso-cacase/CRISPRdirect_crawl#1]
First, I want to say thanks for your Perl script of searching gRNA, and I just have a little question that really need your help. I want to assign my own genome data through 'db'        => 'genome' in command parameters, but what should I do? Play your answer.

**Comment by meso-cacase** [comment]
Thank you for using the Perl script. Unfortunately you cannot use your own genome databases but you can select the `db` parameter from more than 200 species which are supported by [CRISPRdirect](http://crispr.dbcls.jp/) web server. The full list of supported species is available in the [help page](http://crispr.dbcls.jp/doc/#db_list).

**Comment by tiramisutes** [comment]
Ok，thanks for your reply.
